// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("build")>]
[<assembly: AssemblyProductAttribute("PersonalServer")>]
[<assembly: AssemblyDescriptionAttribute("PersonalServer")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "build"
    let [<Literal>] AssemblyProduct = "PersonalServer"
    let [<Literal>] AssemblyDescription = "PersonalServer"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
